Webcfg Metadata TR181 DML and WEBPA Support
xmidt-org/parodus2ccsp pull request #167
Opened 2020-08-24 11:19 UTC by guruchandru

2020-08-24 11:33 UTC, sadhyama requested changes

2020-08-24 11:33 UTC, sadhyama commented on source/WebConfig/cosa_webconfig_dml.c
> +                WebcfgDebug(("[%s] at [%d]parameter '%s'\n",__FUNCTION__,__LINE__, ParamName));
Double bracket is not required for webcfg logging

2020-08-24 11:33 UTC, sadhyama commented on source/WebConfig/cosa_webconfig_dml.c
> +                WebcfgInfo(("[%s] at [%d]parameter '%s'\n",__FUNCTION__,__LINE__, ParamName));
Make this debug log. Double bracket is not required for webcfg logging

2020-08-24 11:33 UTC, sadhyama commented on source/WebConfig/cosa_webconfig_dml.c
> +		        /* if(docValue != NULL)
cleanup code.

2020-08-24 11:33 UTC, sadhyama commented on source/WebConfig/cosa_webconfig_dml.c
> +                WebcfgInfo(("[%s] at [%d]parameter '%s'\n",__FUNCTION__,__LINE__, ParamName));
make it to debug and remove double bracket

2020-08-24 11:33 UTC, sadhyama commented on source/WebConfig/cosa_webconfig_dml.c
> +		     /*    if(versionValue != NULL)
check if free is required, else remove and cleanup this code.

2020-08-24 11:33 UTC, sadhyama commented on source/WebConfig/cosa_webconfig_dml.c
> + 	WebcfgError(("Unsupported parameter '%s'\n", ParamName));
Remove double bracket

2020-08-24 11:33 UTC, sadhyama commented on source/WebConfig/cosa_webconfig_internal.c
> +                                      paramVal[k]->parameterValue = strdup(docvalue);
Would suggest to make either strdup or strndup to make it uniform, as strdup is being used in if case and strndup in else case. Check all cases.

2020-08-27 10:12 UTC, shilpa24balaji approved these changes

2020-08-27 10:19 UTC, sadhyama approved these changes

2020-08-27 10:19 UTC, sadhyama commented on source/WebConfig/cosa_webconfig_dml.c
> +			WebcfgInfo("SupportedDocs set is Not supported\n");
We can make this as debug log as dmcli will return CCSP_ERR_NOT_WRITABLE.

2020-08-27 10:19 UTC, sadhyama commented on source/WebConfig/cosa_webconfig_dml.c
> +			WebcfgInfo("SupportedSchemaVersion set is Not supported\n");
Make this as debug log as dmcli will return CCSP_ERR_NOT_WRITABLE.

2020-08-27 11:56 UTC, merged