RDKB-38989 - Remove the log agent dependencies of webpa module
xmidt-org/parodus2ccsp pull request #217
Opened 2022-01-13 07:46 UTC by gururaajar

Reason for change: Removed logagent from parodus2ccsp
Test Procedure: Build and verified
Risks: Low
Signed-off-by: Gururaaja ESR <gururaja_erodesriranganramlingham@comcast.com>

2022-01-18 07:29 UTC, sadhyama requested changes

2022-01-18 07:29 UTC, sadhyama commented on source/broadband/webpa_internal.c
>  "Device.X_RDKCENTRAL-COM_Webpa.",
If we are removing an entry from objectList , then object level1 count also need to modified accordingly here line 37 and line 40,
https://github.com/xmidt-org/parodus2ccsp/blob/4a73f734e0c3b609f2567817a5824b0a13ec7083/source/broadband/include/webpa_internal.h#L37

2022-01-19 11:38 UTC, sadhyama approved these changes

2022-01-19 15:18 UTC, karuna2git approved these changes

2022-01-19 15:37 UTC, merged